const SortOption = {
  COURSE_SORT_ASC: "COURSE_SORT_ASC",
  COURSE_SORT_DESC: "COURSE_SORT_DESC",
  YEAR_SORT_ASC: "YEAR_SORT_ASC",
  YEAR_SORT_DESC: "YEAR_SORT_DESC",
  NAME_SORT_ASC: "NAME_SORT_ASC",
  NAME_SORT_DESC: "NAME_SORT_DESC",
  PROGRAM_SORT: "PROGRAM_SORT",
};

export default SortOption;
